# Generated by Django 5.1.3 on 2024-12-03 19:54

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Practitioner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fname", models.CharField(max_length=128)),
                ("lname", models.CharField(max_length=128)),
                ("mname", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "abstract": False,
                "default_related_name": "practitioners",
            },
            bases=(models.Model, core.models.AppModelMixin),
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(db_index=True, max_length=512, unique=True)),
                ("snomed_code", models.CharField(help_text="Synonyms: `concept identifier`, `conceptid`.", max_length=64)),
                ("snomed_name", models.CharField(max_length=512)),
            ],
            options={
                "abstract": False,
                "default_related_name": "specialties",
            },
            bases=(models.Model, core.models.AppModelMixin),
        ),
    ]
