# Generated by Django 5.1.3 on 2024-12-03 19:54

import phonenumber_field.modelfields
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fname", models.CharField(max_length=128)),
                ("lname", models.CharField(max_length=128)),
                ("mname", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True)),
                ("phone", phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, unique=True)),
            ],
            options={
                "abstract": False,
                "default_related_name": "patients",
            },
            bases=(models.Model, core.models.AppModelMixin),
        ),
    ]
